# config.yaml
# search_api: tavily
search_api: duckduckgo

default_report_structure: |
  Use this structure to create a report on the user-provided topic:

  ### Introduction (no research needed)
     - Brief overview of the topic area

  ### Main Body Sections:
     - Each section should focus on a sub-topic of the user-provided topic

  ### Conclusion
     - Aim for 1 structural element (either a list or table) that distills the main body sections 
     - Provide a concise summary of the report

number_of_queries: 2
planner_provider: "groq"
planner_model: "gemma2-9b-it"
# planner_model: "mixtral-8x7b-32768"
# planner_model: "llama-3.1-8b-instant"
# planner_model: "deepseek-r1-distill-llama-70b"

query_writer_provider: "groq"
# query_writer_model: "gemma2-9b-it"
# query_writer_model: "llama-3.1-8b-instant"
query_writer_model: "mixtral-8x7b-32768"
# query_writer_model: "deepseek-r1-distill-llama-70b"

section_writer_provider: "groq"
section_writer_model: "mixtral-8x7b-32768"
# section_writer_model: "qwen-2.5-32b"
# section_writer_model: "llama-3.3-70b-versatile"

section_grader_provider: "groq"
section_grader_model: "llama-3.1-8b-instant"
# section_grader_model: "mixtral-8x7b-32768"
# section_grader_model: "llama-3.3-70b-versatile"

final_section_writer_provider: "groq"
# final_section_writer_model: "mixtral-8x7b-32768"
final_section_writer_model: "qwen-2.5-32b"
# final_section_writer_model: "llama-3.3-70b-versatile"

# search_iterations: 1
max_number_of_reflection: 2
